name: Main
on:
  push:
    branches:
      - main

jobs:
  deploy-prd-skip-verification:
    name: Deploy prd skip verification
    if: ${{ endsWith(github.event.head_commit.message, 'skip verification')}}
    runs-on: ubuntu-latest
    environment: prd-skip-verification
    concurrency: prd-${{ github.ref }}
    steps:
      - name: Deploy
        run: |-
          echo Deploy prd
  deploy-prd:
    name: Deploy prd
    if: ${{ !endsWith(github.event.head_commit.message, 'skip verification')}}
    runs-on: ubuntu-latest
    environment: prd
    concurrency: prd-${{ github.ref }}
    steps:
      - name: Deploy
        run: |-
          echo Deploy prd
          
