name: Main
on:
  push:
#    branches:
#      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: test
    concurrency: test-${{ github.ref }}
    steps:
      - name: Debug commit message
        run: |-
          echo ${{ github.event.head_commit.message }}
      - name: Debug GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Deploy
        run: |-
          echo Deploy
          
